export enum GatewayMethod {
  CARD = 'CARD',
  BANCOLOMBIA_TRANSFER = 'BANCOLOMBIA_TRANSFER',
  BANCOLOMBIA_QR = 'BANCOLOMBIA_QR',
  NEQUI = 'NEQUI',
  PSE = 'PSE',
  BANCOLOMBIA_COLLECT = 'BANCOLOMBIA_COLLECT',
  PCOL = 'PCOL',
}
